package InterfaceOperationApp;


/**
* InterfaceOperationApp/InterfaceOperatios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./InterfaceOperations.idl
* Friday, February 24, 2023 11:20:09 AM EST
*/

public interface InterfaceOperatios extends InterfaceOperatiosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceOperatios
