package InterfaceOperationApp;

/**
* InterfaceOperationApp/InterfaceOperatiosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./InterfaceOperations.idl
* Thursday, February 23, 2023 1:34:51 AM EST
*/

public final class InterfaceOperatiosHolder implements org.omg.CORBA.portable.Streamable
{
  public InterfaceOperationApp.InterfaceOperatios value = null;

  public InterfaceOperatiosHolder ()
  {
  }

  public InterfaceOperatiosHolder (InterfaceOperationApp.InterfaceOperatios initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InterfaceOperationApp.InterfaceOperatiosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InterfaceOperationApp.InterfaceOperatiosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InterfaceOperationApp.InterfaceOperatiosHelper.type ();
  }

}
