package InterfaceOperationApp;


/**
* InterfaceOperationApp/InterfaceOperatios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./InterfaceOperations.idl
* Thursday, February 23, 2023 1:34:51 AM EST
*/

public interface InterfaceOperatios extends InterfaceOperatiosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceOperatios
